version: 2
updates:
  # Python dependencies (Poetry managed)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "steam-manifest-team"
    assignees:
      - "steam-manifest-team"
    commit-message:
      prefix: "⬆️"
      prefix-development: "⬆️ dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "poetry"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "httpx"
        update-types: ["version-update:semver-major"]
      - dependency-name: "gitpython"
        update-types: ["version-update:semver-major"]
    # Poetry-specific configuration
    versioning-strategy: "increase"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "steam-manifest-team"
    commit-message:
      prefix: "⬆️ actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"